/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createClient;


import clientDetails.*;
import prototypePattern.*;
import observerPattern.*;

import static prototypePattern.Amnt.amnt;
import static prototypePattern.Bankacntnmbr.bankacntnmbr;
import static prototypePattern.CrctFctr.crctFctr;
import static prototypePattern.FnncInst.fnncInst;
import static prototypePattern.Lastmonth.lastmonth;
import static prototypePattern.Mesurementnumber.mesurementnumber;
import static prototypePattern.Msrmdpst.msrmdpst;
import static prototypePattern.NmbrfuelqnttIndc.nmbrfuelqnttIndc;
import static prototypePattern.Pymnmthd.pymnmthd;
import static prototypePattern.Qnttrqst.qnttrqst;
import static prototypePattern.Rcptamnt.rcptamnt;
import static prototypePattern.Thismonth.thismonth;
import static prototypePattern.Trnsdate.trnsdate;
import static prototypePattern.Usage.usage;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import static createClient.BusinessName.*;
import static createClient.BusinessNumber.*;
import static createClient.BusinessMeterday.*;
import static createClient.BusinessAddress.*;

import static createClient.GeneralName.*;
import static createClient.GeneralNumber.*;
import static createClient.GeneralMeterday.*;
import static createClient.GeneralAddress.*;
import java.awt.Color;
import javax.swing.UIManager;


/**
 *
 * @author wjdgh
 */
public class MainView extends javax.swing.JFrame {

    int clientcheak = 0;
    static int selectedRowIndex; //테이블 행
    static int selectedColumnIndex; //테이블 열
    DefaultTableModel generalClientTable;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentInformationDialog = new javax.swing.JDialog();
        PaymentInformationPN = new javax.swing.JPanel();
        msrmDpstJL1 = new javax.swing.JLabel();
        msrmDpstTF1 = new javax.swing.JTextField();
        fnncInstJL1 = new javax.swing.JLabel();
        bankacntNmbrTF1 = new javax.swing.JTextField();
        bankacntNmbrJL1 = new javax.swing.JLabel();
        pymnMthdJL1 = new javax.swing.JLabel();
        UpdateBT = new javax.swing.JButton();
        UpdateCancleBT = new javax.swing.JButton();
        pymnMthdCB = new javax.swing.JComboBox<>();
        fnncInstCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Citygasbill = new javax.swing.JPanel();
        ClientListTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        BusinessClientListTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        GeneralClientListTable = new javax.swing.JTable();
        clientSearchTF = new javax.swing.JTextField();
        ClientCheakBT = new javax.swing.JButton();
        clientSearchBT = new javax.swing.JButton();
        clientDetails = new javax.swing.JPanel();
        clientNameJL = new javax.swing.JLabel();
        clientNumberJL = new javax.swing.JLabel();
        clientAddressJL = new javax.swing.JLabel();
        clientNameTF = new javax.swing.JTextField();
        clientNumberTF = new javax.swing.JTextField();
        clientAddressTF = new javax.swing.JTextField();
        meterNumberJL = new javax.swing.JLabel();
        meterNumberTF = new javax.swing.JTextField();
        lastMonthTF = new javax.swing.JTextField();
        lastMonthJL = new javax.swing.JLabel();
        thisMonthJL = new javax.swing.JLabel();
        thisMonthTF = new javax.swing.JTextField();
        crctFctrJL = new javax.swing.JLabel();
        crctFctrTF = new javax.swing.JTextField();
        usageJL = new javax.swing.JLabel();
        usageTF = new javax.swing.JTextField();
        nmbrfuelQnttIndcJL = new javax.swing.JLabel();
        nmbrfuelQnttIndcTF = new javax.swing.JTextField();
        qnttrQstJL = new javax.swing.JLabel();
        qnttrQstTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        msrmDpstTF = new javax.swing.JTextField();
        msrmDpstJL = new javax.swing.JLabel();
        fnncInstJL = new javax.swing.JLabel();
        fnncInstTF = new javax.swing.JTextField();
        bankacntNmbrJL = new javax.swing.JLabel();
        bankacntNmbrTF = new javax.swing.JTextField();
        trnsDateJL = new javax.swing.JLabel();
        trnsDateTF = new javax.swing.JTextField();
        ClientCheakBT1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rcptAmntJL = new javax.swing.JLabel();
        rcptAmntTF = new javax.swing.JTextField();
        pymnMthdJL = new javax.swing.JLabel();
        pymnMthdTF = new javax.swing.JTextField();
        amntJL = new javax.swing.JLabel();
        amntTF = new javax.swing.JTextField();
        paymentUpdateBT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        savingJL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        PaymentInformationPN.setBorder(javax.swing.BorderFactory.createTitledBorder("납부정보 변경"));

        msrmDpstJL1.setText("예금주명 :");

        fnncInstJL1.setText("금융기관 :");

        bankacntNmbrJL1.setText("계좌번호 :");

        pymnMthdJL1.setText("납부방법 :");

        UpdateBT.setText("확인");
        UpdateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTActionPerformed(evt);
            }
        });

        UpdateCancleBT.setText("취소");
        UpdateCancleBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCancleBTActionPerformed(evt);
            }
        });

        pymnMthdCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "자동납부", "수동납부" }));

        fnncInstCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "국민은행", "우리은행", "신한은행", "하나은행", "한국씨티은행", "대구은행", "부산은행", "광주은행", "전북은행", "경남은행", "제주은행", "농협", "수협", "한국산업은행", "기업은행", "수출입은행", "신협", "우체국", "새마을금고", "산림조합", "저축은행" }));

        javax.swing.GroupLayout PaymentInformationPNLayout = new javax.swing.GroupLayout(PaymentInformationPN);
        PaymentInformationPN.setLayout(PaymentInformationPNLayout);
        PaymentInformationPNLayout.setHorizontalGroup(
            PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentInformationPNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(UpdateCancleBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(UpdateBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaymentInformationPNLayout.createSequentialGroup()
                            .addComponent(pymnMthdJL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pymnMthdCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaymentInformationPNLayout.createSequentialGroup()
                            .addComponent(fnncInstJL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fnncInstCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaymentInformationPNLayout.createSequentialGroup()
                            .addComponent(msrmDpstJL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(msrmDpstTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaymentInformationPNLayout.createSequentialGroup()
                            .addComponent(bankacntNmbrJL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bankacntNmbrTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaymentInformationPNLayout.setVerticalGroup(
            PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentInformationPNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msrmDpstJL1)
                    .addComponent(msrmDpstTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnncInstJL1)
                    .addComponent(fnncInstCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankacntNmbrJL1)
                    .addComponent(bankacntNmbrTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentInformationPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pymnMthdJL1)
                    .addComponent(pymnMthdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateCancleBT)
                .addContainerGap())
        );

        javax.swing.GroupLayout PaymentInformationDialogLayout = new javax.swing.GroupLayout(PaymentInformationDialog.getContentPane());
        PaymentInformationDialog.getContentPane().setLayout(PaymentInformationDialogLayout);
        PaymentInformationDialogLayout.setHorizontalGroup(
            PaymentInformationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentInformationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentInformationPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaymentInformationDialogLayout.setVerticalGroup(
            PaymentInformationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentInformationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentInformationPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Citygasbill.setBorder(javax.swing.BorderFactory.createTitledBorder("도시가스청구서"));
        Citygasbill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BusinessClientListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "고객번호", "고객이름", "고객주소", "최근 검침일"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BusinessClientListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusinessClientListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BusinessClientListTable);
        if (BusinessClientListTable.getColumnModel().getColumnCount() > 0) {
            BusinessClientListTable.getColumnModel().getColumn(0).setMinWidth(50);
            BusinessClientListTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            BusinessClientListTable.getColumnModel().getColumn(0).setMaxWidth(50);
            BusinessClientListTable.getColumnModel().getColumn(1).setMinWidth(100);
            BusinessClientListTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            BusinessClientListTable.getColumnModel().getColumn(1).setMaxWidth(100);
            BusinessClientListTable.getColumnModel().getColumn(2).setMinWidth(100);
            BusinessClientListTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            BusinessClientListTable.getColumnModel().getColumn(2).setMaxWidth(100);
            BusinessClientListTable.getColumnModel().getColumn(3).setMinWidth(320);
            BusinessClientListTable.getColumnModel().getColumn(3).setPreferredWidth(320);
            BusinessClientListTable.getColumnModel().getColumn(3).setMaxWidth(320);
            BusinessClientListTable.getColumnModel().getColumn(4).setMinWidth(120);
            BusinessClientListTable.getColumnModel().getColumn(4).setPreferredWidth(120);
            BusinessClientListTable.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        ClientListTab.addTab("기업 고객", jScrollPane1);

        GeneralClientListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "고객번호", "고객이름", "고객주소", "최근 검침일"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GeneralClientListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralClientListTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GeneralClientListTable);
        if (GeneralClientListTable.getColumnModel().getColumnCount() > 0) {
            GeneralClientListTable.getColumnModel().getColumn(0).setMinWidth(50);
            GeneralClientListTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            GeneralClientListTable.getColumnModel().getColumn(0).setMaxWidth(50);
            GeneralClientListTable.getColumnModel().getColumn(1).setMinWidth(100);
            GeneralClientListTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            GeneralClientListTable.getColumnModel().getColumn(1).setMaxWidth(100);
            GeneralClientListTable.getColumnModel().getColumn(2).setMinWidth(100);
            GeneralClientListTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            GeneralClientListTable.getColumnModel().getColumn(2).setMaxWidth(100);
            GeneralClientListTable.getColumnModel().getColumn(3).setMinWidth(320);
            GeneralClientListTable.getColumnModel().getColumn(3).setPreferredWidth(320);
            GeneralClientListTable.getColumnModel().getColumn(3).setMaxWidth(320);
            GeneralClientListTable.getColumnModel().getColumn(4).setMinWidth(120);
            GeneralClientListTable.getColumnModel().getColumn(4).setPreferredWidth(120);
            GeneralClientListTable.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        ClientListTab.addTab("일반 고객", jScrollPane2);

        Citygasbill.add(ClientListTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 688, 217));

        clientSearchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSearchTFActionPerformed(evt);
            }
        });
        Citygasbill.add(clientSearchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));

        ClientCheakBT.setText("조회");
        ClientCheakBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientCheakBTActionPerformed(evt);
            }
        });
        Citygasbill.add(ClientCheakBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, -1));

        clientSearchBT.setText("검색");
        clientSearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSearchBTActionPerformed(evt);
            }
        });
        Citygasbill.add(clientSearchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, -1));

        clientDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("상세정보"));

        clientNameJL.setText("고객명 :");

        clientNumberJL.setText("고객번호 :");

        clientAddressJL.setText("고객주소 :");

        meterNumberJL.setText("계량기번호 :");

        lastMonthJL.setText("전월지침 :");

        thisMonthJL.setText("당월지침 :");

        crctFctrJL.setText("보정계수 :");

        usageJL.setText("사용량 :");

        nmbrfuelQnttIndcJL.setText("열량계수 :");

        qnttrQstJL.setText("청구량 :");

        javax.swing.GroupLayout clientDetailsLayout = new javax.swing.GroupLayout(clientDetails);
        clientDetails.setLayout(clientDetailsLayout);
        clientDetailsLayout.setHorizontalGroup(
            clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clientDetailsLayout.createSequentialGroup()
                        .addComponent(nmbrfuelQnttIndcJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nmbrfuelQnttIndcTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientDetailsLayout.createSequentialGroup()
                        .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(clientDetailsLayout.createSequentialGroup()
                                .addComponent(qnttrQstJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qnttrQstTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clientDetailsLayout.createSequentialGroup()
                                .addComponent(usageJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(206, 206, 206))
                    .addGroup(clientDetailsLayout.createSequentialGroup()
                        .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clientNameJL)
                            .addComponent(meterNumberJL)
                            .addComponent(clientAddressJL)
                            .addComponent(thisMonthJL))
                        .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(clientDetailsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(thisMonthTF, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(meterNumberTF))
                                .addGap(26, 26, 26)
                                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crctFctrJL, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastMonthJL, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(crctFctrTF, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(lastMonthTF)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clientDetailsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientAddressTF)
                                    .addGroup(clientDetailsLayout.createSequentialGroup()
                                        .addComponent(clientNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                        .addComponent(clientNumberJL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clientNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientDetailsLayout.setVerticalGroup(
            clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameJL)
                    .addComponent(clientNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientNumberJL)
                    .addComponent(clientNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddressJL)
                    .addComponent(clientAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meterNumberJL)
                    .addComponent(meterNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastMonthJL)
                    .addComponent(lastMonthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thisMonthJL)
                    .addComponent(thisMonthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crctFctrJL)
                    .addComponent(crctFctrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usageJL)
                    .addComponent(usageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmbrfuelQnttIndcJL)
                    .addComponent(nmbrfuelQnttIndcTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qnttrQstJL)
                    .addComponent(qnttrQstTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Citygasbill.add(clientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 440, 220));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("자동납부 이체안내"));

        msrmDpstJL.setText("예금주명 :");

        fnncInstJL.setText("금융기관 :");

        bankacntNmbrJL.setText("계좌번호 :");

        trnsDateJL.setText("이체일자 :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(msrmDpstJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msrmDpstTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fnncInstJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnncInstTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bankacntNmbrJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankacntNmbrTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(trnsDateJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trnsDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msrmDpstJL)
                    .addComponent(msrmDpstTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnncInstJL)
                    .addComponent(fnncInstTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankacntNmbrJL)
                    .addComponent(bankacntNmbrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trnsDateJL)
                    .addComponent(trnsDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Citygasbill.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 240, 150));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        ClientCheakBT1.setText("조회");
        ClientCheakBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientCheakBT1ActionPerformed(evt);
            }
        });
        Citygasbill.add(ClientCheakBT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("요금납부 정보"));

        rcptAmntJL.setText("금액수납일 :");

        pymnMthdJL.setText("납부방법 :");

        amntJL.setText("금액 :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rcptAmntJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rcptAmntTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pymnMthdJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pymnMthdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(amntJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amntTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rcptAmntJL)
                    .addComponent(rcptAmntTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pymnMthdJL)
                    .addComponent(pymnMthdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amntJL)
                    .addComponent(amntTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Citygasbill.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 240, -1));

        paymentUpdateBT.setText("자동이체 정보 변경");
        paymentUpdateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentUpdateBTActionPerformed(evt);
            }
        });
        Citygasbill.add(paymentUpdateBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 240, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 32667));

        savingJL.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(savingJL)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savingJL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Citygasbill.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 440, 45));

        jMenu1.setText("파일(File)");

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuExit.setText("종료(Exit)");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Citygasbill, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Citygasbill, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusinessClientListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusinessClientListTableMouseClicked
        DefaultTableModel businessClientTable = (DefaultTableModel)BusinessClientListTable.getModel();
        this.selectedRowIndex = BusinessClientListTable.getSelectedRow();
        int index = BusinessClientListTable.getSelectedRow();
        int sum = 0;

       
       //텍스트필드에 고객명 출력
       clientNameTF.setText(businessClientTable.getValueAt(selectedRowIndex, 2).toString());
       //텍스트필드에 고객번호 출력
       clientNumberTF.setText(businessClientTable.getValueAt(selectedRowIndex, 1).toString());
       //텍스트필드에 고객주소 출력
       clientAddressTF.setText(businessClientTable.getValueAt(selectedRowIndex, 3).toString());
       
       //고객수 만큼 읽고, 테이블 행 값에따라 해당 메서드 값을 읽어옴
       for(int i=0; i < generalName.length; i++){
           if(selectedRowIndex == i){
                //기업 고객 상세정보
                meterNumberTF.setText(mesurementnumber[i].toString());
                lastMonthTF.setText(lastmonth[i].toString());
                thisMonthTF.setText(thismonth[i].toString());
                crctFctrTF.setText(crctFctr[i].toString());
                usageTF.setText(usage[i].toString() + "m^3");
                nmbrfuelQnttIndcTF.setText(nmbrfuelqnttIndc[i].toString());
                qnttrQstTF.setText(qnttrqst[i].toString() + "MJ");
                
                //기업 고객 자동납부 이체안내
                msrmDpstTF.setText(msrmdpst[i].toString());
                fnncInstTF.setText(fnncInst[i].toString());
                bankacntNmbrTF.setText(bankacntnmbr[i].toString());
                trnsDateTF.setText(trnsdate[i].toString());
                
                //기업 고객 요금납부 정보
                rcptAmntTF.setText(rcptamnt[i].toString());
                pymnMthdTF.setText(pymnmthd[i].toString());
                amntTF.setText(amnt[i].toString() + "원");
                
                // amnt(금액) 합계를 구한다.
                for(int j=0 ; j < amnt.length; j++){
                    sum += Integer.parseInt(amnt[j]);
                }
                
                //평균 금액 이하이면 잘 실천하고 있다는 jlabel 출력.
                if(Integer.parseInt(amnt[i]) >= sum/amnt.length){
                    savingJL.setText("기업 " + businessClientTable.getValueAt(selectedRowIndex, 2).toString() + "는(은) 평균사용량 대비 가스절약을 잘 실천하지 못하고 있습니다.");
                    savingJL.setForeground(Color.red);
                } else{
                    savingJL.setText("기업 " + businessClientTable.getValueAt(selectedRowIndex, 2).toString() + "는(은) 평균사용량 대비 가스절약을 잘 실천하고 있습니다.");
                    savingJL.setForeground(Color.blue);
                }
           }
       }
    }//GEN-LAST:event_BusinessClientListTableMouseClicked

    private void clientSearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSearchBTActionPerformed
        TableRowSorter<TableModel> businessSorter = new TableRowSorter<TableModel>(((DefaultTableModel) BusinessClientListTable.getModel()));
        TableRowSorter<TableModel> generalSorter = new TableRowSorter<TableModel>(((DefaultTableModel) GeneralClientListTable.getModel()));
        
        businessSorter.setRowFilter(RowFilter.regexFilter(clientSearchTF.getText()));
        generalSorter.setRowFilter(RowFilter.regexFilter(clientSearchTF.getText()));
        
        BusinessClientListTable.setRowSorter(businessSorter);
        GeneralClientListTable.setRowSorter(generalSorter);
    }//GEN-LAST:event_clientSearchBTActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void GeneralClientListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralClientListTableMouseClicked
        this.generalClientTable = (DefaultTableModel)GeneralClientListTable.getModel();
        this.selectedRowIndex = GeneralClientListTable.getSelectedRow();
        this.selectedColumnIndex = GeneralClientListTable.getSelectedColumn();
        int index = GeneralClientListTable.getSelectedRow();
        int sum = 0;
        // 문자열로 들어가있는 금액을 정수형으로 변환
        //int value = Integer.parseInt(amnt[0]);
        
        //Mesurementnumber mesuremennumber = new Mesurementnumber(mesurementnumber);
       
       //텍스트필드에 고객명 출력
       clientNameTF.setText(generalClientTable.getValueAt(selectedRowIndex, 2).toString());
       //텍스트필드에 고객번호 출력
       clientNumberTF.setText(generalClientTable.getValueAt(selectedRowIndex, 1).toString());
       //텍스트필드에 고객주소 출력
       clientAddressTF.setText(generalClientTable.getValueAt(selectedRowIndex, 3).toString());
       
       //고객수 만큼 읽고, 테이블 행 값에따라 해당 메서드 값을 읽어옴
       for(int i=0; i < generalName.length; i++){
           if(selectedRowIndex == i){
                //일반 고객 상세정보
                meterNumberTF.setText(mesurementnumber[i].toString());
                lastMonthTF.setText(lastmonth[i].toString());
                thisMonthTF.setText(thismonth[i].toString());
                crctFctrTF.setText(crctFctr[i].toString());
                usageTF.setText(usage[i].toString() + "m^3");
                nmbrfuelQnttIndcTF.setText(nmbrfuelqnttIndc[i].toString());
                qnttrQstTF.setText(qnttrqst[i].toString() + "MJ");
                
                //일반 고객 자동납부 이체안내
                msrmDpstTF.setText(msrmdpst[i].toString());
                fnncInstTF.setText(fnncInst[i].toString());
                bankacntNmbrTF.setText(bankacntnmbr[i].toString());
                trnsDateTF.setText(trnsdate[i].toString());
                
                //일반 고객 요금납부 정보
                rcptAmntTF.setText(rcptamnt[i].toString());
                pymnMthdTF.setText(pymnmthd[i].toString());
                amntTF.setText(amnt[i].toString() + "원");
                
                 // amnt(금액) 합계를 구한다.
                for(int j=0 ; j < amnt.length; j++){
                    sum += Integer.parseInt(amnt[j]);
                }
                
                //평균 금액 이하이면 잘 실천하고 있다는 jlabel 출력.
                if(Integer.parseInt(amnt[i]) >= sum/amnt.length){
                    savingJL.setText(generalClientTable.getValueAt(selectedRowIndex, 2).toString() + " 고객님은 평균 사용량대비 가스절약을 잘 실천하지 못하고 있습니다.");
                    savingJL.setForeground(Color.red);
                } else{
                    savingJL.setText(generalClientTable.getValueAt(selectedRowIndex, 2).toString() + " 고객님은 평균 사용량대비 가스절약을 잘 실천하고 있습니다.");
                    savingJL.setForeground(Color.blue);
                }
           }
           
          
       }
       
    }//GEN-LAST:event_GeneralClientListTableMouseClicked

    private void ClientCheakBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientCheakBTActionPerformed
        DefaultTableModel businessClientTable = (DefaultTableModel)BusinessClientListTable.getModel();
        DefaultTableModel generalClientTable = (DefaultTableModel)GeneralClientListTable.getModel();

        if(clientcheak==0){
            for(int i=0; i < businessName.length; i++)
            {
                businessClientTable.addRow(new Object[] {i+1, businessNumber[i], businessName[i], businessAddress[i], businessMeterday[i]});
            }

            for(int i=0; i < generalName.length; i++){
                generalClientTable.addRow(new Object[] {i+1, generalNumber[i], generalName[i], generalAddress[i], generalMeterday[i]});
            }

            clientcheak++;
        }

        else{
            //기업 고객정보와 일반 고객정보 테이블을 초기화
            businessClientTable.setNumRows(0);
            generalClientTable.setNumRows(0);
            JOptionPane.showMessageDialog(null, "다시 한번 조회버튼을 눌러주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
            clientcheak--;
        }

    }//GEN-LAST:event_ClientCheakBTActionPerformed

    private void ClientCheakBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientCheakBT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientCheakBT1ActionPerformed

    private void paymentUpdateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentUpdateBTActionPerformed
        PaymentInformationDialog.setVisible(true);
        PaymentInformationDialog.setTitle("납부정보 변경");
        PaymentInformationDialog.setSize(250,250);
        PaymentInformationDialog.setLocation(250, 250);
    }//GEN-LAST:event_paymentUpdateBTActionPerformed

    private void UpdateCancleBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCancleBTActionPerformed
        PaymentInformationDialog.setVisible(false);
    }//GEN-LAST:event_UpdateCancleBTActionPerformed

    private void UpdateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTActionPerformed
        PaymentInformation pi = new PaymentInformation();
        
        Msrmdpst msrdpst = new Msrmdpst(pi);
        FnncInst fnclnst = new FnncInst(pi);
        Bankacntnmbr bank = new Bankacntnmbr(pi);
        Pymnmthd pym = new Pymnmthd(pi);
        
        //int s = selectedRowIndex;
        String m = msrmDpstTF1.getText();
        String f = fnncInstCB.getSelectedItem().toString();
        String b = bankacntNmbrTF1.getText();
        String p = pymnMthdCB.getSelectedItem().toString();
        
        //일반 고객 수 만큼 for문 반복
        for(int s=0; s < generalName.length; s++){
           //선택한 행값과 s값이 동일하면 값 변경 
           if(selectedRowIndex == s){
                //입력받은 값 변경
                pi.setPaymentInformation(m, f, b, p, s);
           }
        }
        
        //변경이 완료되었다는 팝업창
        JOptionPane.showMessageDialog(null, selectedRowIndex+1 +"번째 고객의 납부정보가 변경되었습니다.", "Warning", JOptionPane.WARNING_MESSAGE);
        PaymentInformationDialog.setVisible(false);
    }//GEN-LAST:event_UpdateBTActionPerformed

    private void clientSearchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSearchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSearchTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
        
         Client client = null;
         //Client를 client로 null값 초기화
         
           BuildClient clientBusiness = new BuildBusiness();
           BuildClient clientGeneral = new BuildGeneral();
           //BuildBusiness로 업캐스팅해서 clientBusiness에 담는다.
           
           client = clientBusiness.categoryClient("business");
           //BuildBusiness에 if문으로 인하여 business가 저장된다.
           
           System.out.println("*****************************************************");
           client = clientGeneral.categoryClient("general");
           //clientGeneral에 if문으로 인하여 general이 저장된다.
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BusinessClientListTable;
    private javax.swing.JPanel Citygasbill;
    private javax.swing.JButton ClientCheakBT;
    private javax.swing.JButton ClientCheakBT1;
    private javax.swing.JTabbedPane ClientListTab;
    private javax.swing.JTable GeneralClientListTable;
    private javax.swing.JDialog PaymentInformationDialog;
    private javax.swing.JPanel PaymentInformationPN;
    private javax.swing.JButton UpdateBT;
    private javax.swing.JButton UpdateCancleBT;
    private javax.swing.JLabel amntJL;
    private javax.swing.JTextField amntTF;
    private javax.swing.JLabel bankacntNmbrJL;
    private javax.swing.JLabel bankacntNmbrJL1;
    private javax.swing.JTextField bankacntNmbrTF;
    private javax.swing.JTextField bankacntNmbrTF1;
    private javax.swing.JLabel clientAddressJL;
    private javax.swing.JTextField clientAddressTF;
    private javax.swing.JPanel clientDetails;
    private javax.swing.JLabel clientNameJL;
    private javax.swing.JTextField clientNameTF;
    private javax.swing.JLabel clientNumberJL;
    private javax.swing.JTextField clientNumberTF;
    private javax.swing.JButton clientSearchBT;
    private javax.swing.JTextField clientSearchTF;
    private javax.swing.JLabel crctFctrJL;
    private javax.swing.JTextField crctFctrTF;
    private javax.swing.JComboBox<String> fnncInstCB;
    private javax.swing.JLabel fnncInstJL;
    private javax.swing.JLabel fnncInstJL1;
    private javax.swing.JTextField fnncInstTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastMonthJL;
    private javax.swing.JTextField lastMonthTF;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JLabel meterNumberJL;
    private javax.swing.JTextField meterNumberTF;
    private javax.swing.JLabel msrmDpstJL;
    private javax.swing.JLabel msrmDpstJL1;
    private javax.swing.JTextField msrmDpstTF;
    private javax.swing.JTextField msrmDpstTF1;
    private javax.swing.JLabel nmbrfuelQnttIndcJL;
    private javax.swing.JTextField nmbrfuelQnttIndcTF;
    private javax.swing.JButton paymentUpdateBT;
    private javax.swing.JComboBox<String> pymnMthdCB;
    private javax.swing.JLabel pymnMthdJL;
    private javax.swing.JLabel pymnMthdJL1;
    private javax.swing.JTextField pymnMthdTF;
    private javax.swing.JLabel qnttrQstJL;
    private javax.swing.JTextField qnttrQstTF;
    private javax.swing.JLabel rcptAmntJL;
    private javax.swing.JTextField rcptAmntTF;
    private javax.swing.JLabel savingJL;
    private javax.swing.JLabel thisMonthJL;
    private javax.swing.JTextField thisMonthTF;
    private javax.swing.JLabel trnsDateJL;
    private javax.swing.JTextField trnsDateTF;
    private javax.swing.JLabel usageJL;
    private javax.swing.JTextField usageTF;
    // End of variables declaration//GEN-END:variables
}
